### ISSUE TITLE
`replace_value_with` malfunctions in version 0.0.7

### ISSUE THREAD

**Issue by EchoStone1101** [pku-minic/koopa#4]
The `replace_value_with` method implemented in `koopa::ir::entities::FunctionData` malfunctions , as of version 0.0.7.
It works by calling `ValueBuilder` methods on the `ReplaceBuilder` type:
```Rust
pub fn replace_value_with(&mut self, value: Value) -> ReplaceBuilder {
    ReplaceBuilder { dfg: self, value }
}
```
which does this
```Rust
impl<'a> ValueBuilder for ReplaceBuilder<'a> {}
impl<'a> LocalInstBuilder for ReplaceBuilder<'a> {}
```
However, all `ValueBuilder`/`LocalInstBuilder` methods create `ValueData`s with **empty `used_by` set**. Consequently, when calling `replace_value_with` on a `Value` with non-empty `used_by`, the replaced `Value` will appear to not be used by any other `Value`, while at the same time it still shares the same `Value` handle, and is referenced in, say, other instructions. Inconsistency!

On fixing this: to disable this method on used `Value`s by adding assertion is OK, but then there is no way to do what this method implies is possible, that is replacing a referenced `Value` while keeping the same handle. In that case, it will be extremely tedious to write optimization passes for Koopa IR. Say I recognize that two instructions do the same thing, and want to remove the redundant one. I would have to first get rid of all the instructions that (iteratively) rely on it! Yikes.
(The `raw()` builder is also not helpful here, because the `Clone` method clears the `used_by` set.)

(Yes, I found out this **the hard way** when writing optimization passes.)

**Comment by MaxXSoft** [comment]
The core implementation of `replace_value_with` is `ir::dfg::DataFlowGraph::replace_value_with_data`:

https://github.com/pku-minic/koopa/blob/c97c0e1e959b3d2d5cad7ae7034f15e825c30287/src/ir/dfg.rs#L100-L115

As you pointed out, the critical issue of this function is that the `used_by` set of the value data is not updated before the replacement  occurs, so the following patch makes sense:

```rs
pub(in crate::ir) fn replace_value_with_data(&mut self, value: Value, mut data: ValueData) {
  let old = self.values.remove(&value).unwrap();
  // ...
  data.used_by = old.used_by;  // <--
  self.values.insert(value, data);
}
```

> Say I recognize that two instructions do the same thing, and want to remove the redundant one. I would have to first get rid of all the instructions that (iteratively) rely on it!

After fixing the `used_by` issue, if you want to remove the instruction A, which is referenced by another instruction B, you can:

1. Clone the value data of B.
2. Let it reference another valid value.
3. Replace B with the cloned value data.
4. Remove A.

**Comment by EchoStone1101** [comment]
Thanks for the update! This fix will indeed handle the following case:
```log
replace_value_with(instB).some_new_data()

[instA]<---[instB]<---[instC]
              ^
              |
           [instD]
```
where the `ValueData` of `instB` is modified, but the use graph is untouched.

A tiny concern though. I think it would be appreciated if the `Clone` behavior of `ValueData` (that it clears the `used_by` set in the cloned value) is documented explicitly. Otherwise, the effect of `replace_value_with().raw(ref_to_existing_value_data.clone())` is somewhat unclear at the first glance:
```log
replace_value_with(instD).raw(instB_value_data.clone())

[instE]--->[instD]--->[instA]<---[instB]<---[instC]

```
results in
```log
[instE]--->[instB]--->[instA]<---[instB]<---[instC]
```
but not
```log
[instA]<---[instB]<---[instC]
              ^
              |
           [instE]
```
because the `clone()` method of `ValueData` clears `used_by` of cloned `instB` data, which is then replaced by the `used_by` of `instD`.
Now I'm not suggesting that the latter is "the correct behavior"; in fact it's kind of wrong because `replace_value_with` should not eliminate the `Value` handle of D. However, to me the second behavior seems more intuitive at the first glance, not knowing what the `clone` really does.
Maybe a few words in the `raw` builder method will do. Something like "The created `ValueData` does not inherit the `used_by` set of the provided raw data.  See the `Clone` implementation for `ValueData`".

**Comment by MaxXSoft** [comment]
> I think it would be appreciated if the `Clone` behavior of `ValueData` (that it clears the `used_by` set in the cloned value) is documented explicitly.

Actually it does:

https://github.com/pku-minic/koopa/blob/c97c0e1e959b3d2d5cad7ae7034f15e825c30287/src/ir/entities.rs#L486-L496

and also the [docs.rs](https://docs.rs/koopa/latest/koopa/ir/entities/struct.ValueData.html#impl-Clone-for-ValueData).

But I have to admit that this implementation of `Clone` does go against common sense somewhat. 🤦‍♂️

> Maybe a few words in the `raw` builder method will do. Something like "The created `ValueData` does not inherit the `used_by` set of the provided raw data. See the `Clone` implementation for `ValueData`".

That's a great suggestion, thanks a lot! This will be fixed in the next version.
