### ISSUE TITLE
Crates.io请求

### ISSUE THREAD

**Issue by LeoDreamer2004** [pku-minic/koopa#7]
请问老师可以把 issue #4  修复的内容发布到 crates.io 上吗？写作业发现这个问题，已经有人提出了。优化遇到了很大的困难，感谢！

**Comment by MaxXSoft** [comment]
你好！

感谢反馈，刚刚已经发布 `koopa` 0.0.8 版本，你可更新你的 `Cargo.toml` 依赖配置。

祝学习顺利。

**Comment by LeoDreamer2004** [comment]
感谢助教！

> 你好！
> 
> 感谢反馈，刚刚已经发布 `koopa` 0.0.8 版本，你可更新你的 `Cargo.toml` 依赖配置。
> 
> 祝学习顺利。
